export PYENV_ROOT=${HOME}/.pyenv
export PATH=${PYENV_ROOT}/bin:${PATH}
export PATH=${HOME}/.nodebrew/current/bin:${PATH}
export PATH=${HOME}/.local/bin:${PATH}

if command -v pyenv 1>/dev/null 2>&1
then
  eval "$(pyenv init -)"
fi

